### ISSUE TITLE
Bin.launch(String, boolean) is undefined

### ISSUE THREAD

**Issue by tbphong** [gstreamer-java/gst1-javafx-examples#2]
Hi Gstreamer,

I have a error when use your code. 
The method launch(String, boolean) is undefined for the type Bin
Can you help me. Thanks you so much.

**Comment by neilcsmith-net** [comment]
This example repository was abandoned by the person who started it, and will not work with versions of gst1-java-core above 1.0. I'm going to archive it.

JavaFX integration is changing - see https://github.com/gstreamer-java/gst1-java-fx which is also on Maven Central. This requires OpenJFX 13+ for PixelBuffer integration. Some point soon I'll update that library with a few fixes from a client project, and look at an example.

For now, if you need help please use the mailing list at https://groups.google.com/forum/#!forum/gstreamer-java
